#ifndef __FILE_MERGER_H__
#define __FILE_MERGER_H__

/* This file is automatically generated by G+ FileMerger.
   Do not modify the contents to prevent from invalid addressing.
*/ 

#if defined (__GNUC__) || defined (__CC_ARM)	/* 32 bit ARM compiler */

	#include <stdint.h>
	#if defined (__CSRC_USED__)					/* use C source instead of elf obj file */
		extern const uint8_t* MP3_FileMerger_bin_Data;
		#define SEC_START_ADDR MP3_FileMerger_bin_Data
	#else
		extern uint8_t _binary_MP3_FileMerger_bin_start;
		extern uint32_t _binary_MP3_FileMerger_bin_size;

		#define SEC_START_ADDR &_binary_MP3_FileMerger_bin_start
	#endif

#else
	#define SEC_START_ADDR 0
#endif

#define _GROUP_TABLE                   0       	//Group Index:0           Group Name:Group_Table     Group Type:Unknown 
#define _GROUP_TABLE_ADDR              (SEC_START_ADDR + 0x000008)	//Group Addr :0x000008    Group Name:Group_Table     Group Type:Unknown 
#define _KK2020                        0       	//File  Index:0           File  Name:kk2020.mp3 
#define _KK2020_ADDR                   (SEC_START_ADDR + 0x000008)	//File  Addr :0x000008    File  Name:kk2020.mp3 

#endif /* __FILE_MERGER_H__ */
