#ifndef __FILE_MERGER_H__
#define __FILE_MERGER_H__

/* This file is automatically generated by G+ FileMerger.
   Do not modify the contents to prevent from invalid addressing.
*/ 

#if defined (__GNUC__) || defined (__CC_ARM)  || defined (__ICCARM__) 	/* 32 bit ARM compiler */

	#include <stdint.h>
	#if defined (__CSRC_USED__)					/* use C source instead of elf obj file */
		extern const uint8_t* A1801_FileMerger_bin_Data;
		#define SEC_START_ADDR A1801_FileMerger_bin_Data
	#else
		extern uint8_t _binary_A1801_FileMerger_bin_start;
		extern uint32_t _binary_A1801_FileMerger_bin_size;

		#define SEC_START_ADDR &_binary_A1801_FileMerger_bin_start
	#endif

#else
	#define SEC_START_ADDR 0
#endif

#define _GROUP_TABLE                   0       	//Group Index:0           Group Name:Group_Table     Group Type:Unknown 
#define _GROUP_TABLE_ADDR              (SEC_START_ADDR + 0x0000c8)	//Group Addr :0x0000c8    Group Name:Group_Table     Group Type:Unknown 
#define _VIDEOPLAYBACK_16K_32K         0       	//File  Index:0           File  Name:videoplayback_16K_32K.a181 
#define _VIDEOPLAYBACK_16K_32K_ADDR    (SEC_START_ADDR + 0x0000c8)	//File  Addr :0x0000c8    File  Name:videoplayback_16K_32K.a181 
#define _JINGLEBELLS3_16K_32K          1       	//File  Index:1           File  Name:jinglebells3_16K_32K.a181 
#define _JINGLEBELLS3_16K_32K_ADDR     (SEC_START_ADDR + 0x01957e)	//File  Addr :0x01957e    File  Name:jinglebells3_16K_32K.a181 
#define _ESONG6_16K_32K                2       	//File  Index:2           File  Name:esong6_16K_32K.a181 
#define _ESONG6_16K_32K_ADDR           (SEC_START_ADDR + 0x02c544)	//File  Addr :0x02c544    File  Name:esong6_16K_32K.a181 
#define _AINT_16K_32K                  3       	//File  Index:3           File  Name:aint_16K_32K.a181 
#define _AINT_16K_32K_ADDR             (SEC_START_ADDR + 0x0364aa)	//File  Addr :0x0364aa    File  Name:aint_16K_32K.a181 

#endif /* __FILE_MERGER_H__ */
