#ifndef __FILE_MERGER_H__
#define __FILE_MERGER_H__

/* This file is automatically generated by G+ FileMerger.
   Do not modify the contents to prevent from invalid addressing.
*/ 

#if defined (__GNUC__) || defined (__CC_ARM)	/* 32 bit ARM compiler */

	#include <stdint.h>
	#if defined (__CSRC_USED__)					/* use C source instead of elf obj file */
		extern const uint8_t* ROM_bin_Data;
		#define SEC_START_ADDR ROM_bin_Data
	#else
		extern uint8_t _binary_ROM_bin_start;
		extern uint32_t _binary_ROM_bin_size;

		#define SEC_START_ADDR &_binary_ROM_bin_start
	#endif

#else
	#define SEC_START_ADDR 0
#endif

#define _GROUP_TABLE                   0       	//Group Index:0           Group Name:Group_Table     Group Type:Unknown 
#define _GROUP_TABLE_ADDR              (SEC_START_ADDR + 0x000010)	//Group Addr :0x000010    Group Name:Group_Table     Group Type:Unknown 
#define _GPCM3_DEMO                    0       	//File  Index:0           File  Name:GPCM3_DEMO.bin 
#define _GPCM3_DEMO_ADDR               (SEC_START_ADDR + 0x000010)	//File  Addr :0x000010    File  Name:GPCM3_DEMO.bin 
#define _GPCM3_MIDI                    1       	//File  Index:1           File  Name:GPCM3_MIDI.bin 
#define _GPCM3_MIDI_ADDR               (SEC_START_ADDR + 0x28f030)	//File  Addr :0x28f030    File  Name:GPCM3_MIDI.bin 
#define _INSTDRUM                      2       	//File  Index:2           File  Name:instdrum.bin 
#define _INSTDRUM_ADDR                 (SEC_START_ADDR + 0x2aebe4)	//File  Addr :0x2aebe4    File  Name:instdrum.bin 

#endif /* __FILE_MERGER_H__ */
