#ifndef __FILE_MERGER_H__
#define __FILE_MERGER_H__

/* This file is automatically generated by G+ FileMerger.
   Do not modify the contents to prevent from invalid addressing.
*/ 

#if defined (__GNUC__) || defined (__CC_ARM)	/* 32 bit ARM compiler */

	#include <stdint.h>
	#if defined (__CSRC_USED__)					/* use C source instead of elf obj file */
		extern const uint8_t* MS02_FileMerger_bin_Data;
		#define SEC_START_ADDR MS02_FileMerger_bin_Data
	#else
		extern uint8_t _binary_MS02_FileMerger_bin_start;
		extern uint32_t _binary_MS02_FileMerger_bin_size;

		#define SEC_START_ADDR &_binary_MS02_FileMerger_bin_start
	#endif

#else
	#define SEC_START_ADDR 0
#endif

#define _GROUP_TABLE                   0       	//Group Index:0           Group Name:Group_Table     Group Type:Unknown 
#define _GROUP_TABLE_ADDR              (SEC_START_ADDR + 0x000010)	//Group Addr :0x000010    Group Name:Group_Table     Group Type:Unknown 
#define _GPCM1F_VTECH                  0       	//File  Index:0           File  Name:GPCM1F_VTech.lib32 
#define _GPCM1F_VTECH_ADDR             (SEC_START_ADDR + 0x000010)	//File  Addr :0x000010    File  Name:GPCM1F_VTech.lib32 
#define _DRUM_TEST_MID                 1       	//File  Index:1           File  Name:Drum_Test_mid.BIN 
#define _DRUM_TEST_MID_ADDR            (SEC_START_ADDR + 0x02151a)	//File  Addr :0x02151a    File  Name:Drum_Test_mid.BIN 
#define _DRUM_TEST1_MID                2       	//File  Index:2           File  Name:Drum_Test1_mid.BIN 
#define _DRUM_TEST1_MID_ADDR           (SEC_START_ADDR + 0x021794)	//File  Addr :0x021794    File  Name:Drum_Test1_mid.BIN 

#endif /* __FILE_MERGER_H__ */
