#ifndef __FILE_MERGER_H__
#define __FILE_MERGER_H__

/* This file is automatically generated by G+ FileMerger.
   Do not modify the contents to prevent from invalid addressing.
*/ 

#if defined (__GNUC__) || defined (__CC_ARM)	/* 32 bit ARM compiler */

	#include <stdint.h>
	#if defined (__CSRC_USED__)					/* use C source instead of elf obj file */
		extern const uint8_t* PcmROM_bin_Data;
		#define SEC_START_ADDR PcmROM_bin_Data
	#else
		extern uint8_t _binary_PcmROM_bin_start;
		extern uint32_t _binary_PcmROM_bin_size;

		#define SEC_START_ADDR &_binary_PcmROM_bin_start
	#endif

#else
	#define SEC_START_ADDR 0
#endif

#define _GROUP_TABLE                   0       	//Group Index:0           Group Name:Group_Table     Group Type:Unknown 
#define _GROUP_TABLE_ADDR              (SEC_START_ADDR + 0x000048)	//Group Addr :0x000048    Group Name:Group_Table     Group Type:Unknown 
#define _01_OUT                        0       	//File  Index:0           File  Name:01_Out.PCM 
#define _01_OUT_ADDR                   (SEC_START_ADDR + 0x000048)	//File  Addr :0x000048    File  Name:01_Out.PCM 
#define _02_OUT                        1       	//File  Index:1           File  Name:02_Out.PCM 
#define _02_OUT_ADDR                   (SEC_START_ADDR + 0x003c56)	//File  Addr :0x003c56    File  Name:02_Out.PCM 
#define _03_OUT                        2       	//File  Index:2           File  Name:03_Out.PCM 
#define _03_OUT_ADDR                   (SEC_START_ADDR + 0x0076f8)	//File  Addr :0x0076f8    File  Name:03_Out.PCM 
#define _04_OUT                        3       	//File  Index:3           File  Name:04_Out.PCM 
#define _04_OUT_ADDR                   (SEC_START_ADDR + 0x00bf08)	//File  Addr :0x00bf08    File  Name:04_Out.PCM 
#define _05_OUT                        4       	//File  Index:4           File  Name:05_Out.PCM 
#define _05_OUT_ADDR                   (SEC_START_ADDR + 0x00fb0c)	//File  Addr :0x00fb0c    File  Name:05_Out.PCM 
#define _06_OUT                        5       	//File  Index:5           File  Name:06_Out.PCM 
#define _06_OUT_ADDR                   (SEC_START_ADDR + 0x013b46)	//File  Addr :0x013b46    File  Name:06_Out.PCM 
#define _07_OUT                        6       	//File  Index:6           File  Name:07_Out.PCM 
#define _07_OUT_ADDR                   (SEC_START_ADDR + 0x019394)	//File  Addr :0x019394    File  Name:07_Out.PCM 
#define _08_OUT                        7       	//File  Index:7           File  Name:08_Out.PCM 
#define _08_OUT_ADDR                   (SEC_START_ADDR + 0x01dd7c)	//File  Addr :0x01dd7c    File  Name:08_Out.PCM 
#define _09_OUT                        8       	//File  Index:8           File  Name:09_Out.PCM 
#define _09_OUT_ADDR                   (SEC_START_ADDR + 0x0217a2)	//File  Addr :0x0217a2    File  Name:09_Out.PCM 
#define _10_OUT                        9       	//File  Index:9           File  Name:10_Out.PCM 
#define _10_OUT_ADDR                   (SEC_START_ADDR + 0x025afe)	//File  Addr :0x025afe    File  Name:10_Out.PCM 

#endif /* __FILE_MERGER_H__ */
