#ifndef __FILE_MERGER_H__
#define __FILE_MERGER_H__

/* This file is automatically generated by G+ FileMerger.
   Do not modify the contents to prevent from invalid addressing.
*/ 

#if defined (__GNUC__) || defined (__CC_ARM)  || defined (__ICCARM__) 	/* 32 bit ARM compiler */

	#include <stdint.h>
	#if defined (__CSRC_USED__)					/* use C source instead of elf obj file */
		extern const uint8_t* A2000_FileMerger_bin_Data;
		#define SEC_START_ADDR A2000_FileMerger_bin_Data
	#else
		extern uint8_t _binary_A2000_FileMerger_bin_start;
		extern uint32_t _binary_A2000_FileMerger_bin_size;

		#define SEC_START_ADDR &_binary_A2000_FileMerger_bin_start
	#endif

#else
	#define SEC_START_ADDR 0
#endif

#define _GROUP_TABLE                   0       	//Group Index:0           Group Name:Group_Table     Group Type:Unknown 
#define _GROUP_TABLE_ADDR              (SEC_START_ADDR + 0x000064)	//Group Addr :0x000064    Group Name:Group_Table     Group Type:Unknown 
#define _TODAY_32K_MONO_GEAX           0       	//File  Index:0           File  Name:today_32K_Mono_geax.a20 
#define _TODAY_32K_MONO_GEAX_ADDR      (SEC_START_ADDR + 0x000064)	//File  Addr :0x000064    File  Name:today_32K_Mono_geax.a20 
#define _JINGLEBELLS3_32K_32           1       	//File  Index:1           File  Name:jinglebells3_32k_32.bin 
#define _JINGLEBELLS3_32K_32_ADDR      (SEC_START_ADDR + 0x024278)	//File  Addr :0x024278    File  Name:jinglebells3_32k_32.bin 

#endif /* __FILE_MERGER_H__ */
