  .syntax unified
  .arch	armv6-m

  .section .BOOTHEADER , "wa"
  .align 4

  .long    0x58334D43             /* CM3X */
  .long    0x04000100             /* BootCode_LMA */
  .long    0x20000000             /* BootCode_VMA */
  .long    __boot_sec_size
  .long    0xFFFFFFFF             /* IRQ Vector + "BootCode_SEC" section (byte mode) */


  .incbin "User\\BodyOptions.bin" /* BodyOptions.bin was generated by G+IDE for ARM*/
