#ifndef __FILE_MERGER_H__
#define __FILE_MERGER_H__

/* This file is automatically generated by G+ FileMerger.
   Do not modify the contents to prevent from invalid addressing.
*/ 

#if defined (__GNUC__) || defined (__CC_ARM)	/* 32 bit ARM compiler */

	#include <stdint.h>
	#if defined (__CSRC_USED__)					/* use C source instead of elf obj file */
		extern const uint8_t* A1801_FileMerger_bin_Data;
		#define SEC_START_ADDR A1801_FileMerger_bin_Data
	#else
		extern uint8_t _binary_A1801_FileMerger_bin_start;
		extern uint32_t _binary_A1801_FileMerger_bin_size;

		#define SEC_START_ADDR &_binary_A1801_FileMerger_bin_start
	#endif

#else
	#define SEC_START_ADDR 0
#endif

#define _GROUP_TABLE                   0       	//Group Index:0           Group Name:Group_Table     Group Type:Unknown 
#define _GROUP_TABLE_ADDR              (SEC_START_ADDR + 0x000040)	//Group Addr :0x000040    Group Name:Group_Table     Group Type:Unknown 
#define _1_AROBIAN_24K                 0       	//File  Index:0           File  Name:1_arobian_24K.a181 
#define _1_AROBIAN_24K_ADDR            (SEC_START_ADDR + 0x000040)	//File  Addr :0x000040    File  Name:1_arobian_24K.a181 
#define _2_HAKUNAMATATA_24K            1       	//File  Index:1           File  Name:2_hakunamatata_24K.a181 
#define _2_HAKUNAMATATA_24K_ADDR       (SEC_START_ADDR + 0x017296)	//File  Addr :0x017296    File  Name:2_hakunamatata_24K.a181 
#define _3_HOOD_24K                    2       	//File  Index:2           File  Name:3_hood_24K.a181 
#define _3_HOOD_24K_ADDR               (SEC_START_ADDR + 0x02a0b8)	//File  Addr :0x02a0b8    File  Name:3_hood_24K.a181 
#define _4_SPEECHLESS2_24K             3       	//File  Index:3           File  Name:4_speechless2_24K.a181 
#define _4_SPEECHLESS2_24K_ADDR        (SEC_START_ADDR + 0x036472)	//File  Addr :0x036472    File  Name:4_speechless2_24K.a181 
#define _5_TOYSTORY4_24K               4       	//File  Index:4           File  Name:5_toystory4_24K.a181 
#define _5_TOYSTORY4_24K_ADDR          (SEC_START_ADDR + 0x041f08)	//File  Addr :0x041f08    File  Name:5_toystory4_24K.a181 

#endif /* __FILE_MERGER_H__ */
