#ifndef __FILE_MERGER_H__
#define __FILE_MERGER_H__

/* This file is automatically generated by G+ FileMerger.
   Do not modify the contents to prevent from invalid addressing.
*/ 

#if defined (__GNUC__) || defined (__CC_ARM)  || defined (__ICCARM__) 	/* 32 bit ARM compiler */

	#include <stdint.h>
	#if defined (__CSRC_USED__)					/* use C source instead of elf obj file */
		extern const uint8_t* A2000_FileMerger_bin_Data;
		#define SEC_START_ADDR A2000_FileMerger_bin_Data
	#else
		extern uint8_t _binary_A2000_FileMerger_bin_start;
		extern uint32_t _binary_A2000_FileMerger_bin_size;

		#define SEC_START_ADDR &_binary_A2000_FileMerger_bin_start
	#endif

#else
	#define SEC_START_ADDR 0
#endif

#define _GROUP_TABLE                   0       	//Group Index:0           Group Name:Group_Table     Group Type:Unknown 
#define _GROUP_TABLE_ADDR              (SEC_START_ADDR + 0x000014)	//Group Addr :0x000014    Group Name:Group_Table     Group Type:Unknown 
#define _LOOP_R_32                     0       	//File  Index:0           File  Name:loop_r_32.a20 
#define _LOOP_R_32_ADDR                (SEC_START_ADDR + 0x000014)	//File  Addr :0x000014    File  Name:loop_r_32.a20 
#define _LOOP_L_32                     1       	//File  Index:1           File  Name:loop_l_32.a20 
#define _LOOP_L_32_ADDR                (SEC_START_ADDR + 0x016892)	//File  Addr :0x016892    File  Name:loop_l_32.a20 
#define _INTRO2_R_22050                2       	//File  Index:2           File  Name:INTRO2_R_22050.a20 
#define _INTRO2_R_22050_ADDR           (SEC_START_ADDR + 0x02d110)	//File  Addr :0x02d110    File  Name:INTRO2_R_22050.a20 
#define _INTRO2_L_22050                3       	//File  Index:3           File  Name:INTRO2_L_22050.a20 
#define _INTRO2_L_22050_ADDR           (SEC_START_ADDR + 0x0365ae)	//File  Addr :0x0365ae    File  Name:INTRO2_L_22050.a20 

#endif /* __FILE_MERGER_H__ */
