#ifndef __FILE_MERGER_H__
#define __FILE_MERGER_H__

/* This file is automatically generated by G+ FileMerger.
   Do not modify the contents to prevent from invalid addressing.
*/ 

#if defined (__GNUC__) || defined (__CC_ARM)  || defined (__ICCARM__) 	/* 32 bit ARM compiler */

	#include <stdint.h>
	#if defined (__CSRC_USED__)					/* use C source instead of elf obj file */
		extern const uint8_t* A1801_FileMerger_bin_Data;
		#define SEC_START_ADDR A1801_FileMerger_bin_Data
	#else
		extern uint8_t _binary_A1801_FileMerger_bin_start;
		extern uint32_t _binary_A1801_FileMerger_bin_size;

		#define SEC_START_ADDR &_binary_A1801_FileMerger_bin_start
	#endif

#else
	#define SEC_START_ADDR 0
#endif

#define _GROUP_TABLE                   0       	//Group Index:0           Group Name:Group_Table     Group Type:Unknown 
#define _GROUP_TABLE_ADDR              (SEC_START_ADDR + 0x0000c8)	//Group Addr :0x0000c8    Group Name:Group_Table     Group Type:Unknown 
#define _VIDEOPLAYBACK_32K_32          0       	//File  Index:0           File  Name:videoplayback_32k_32.bin 
#define _VIDEOPLAYBACK_32K_32_ADDR     (SEC_START_ADDR + 0x0000c8)	//File  Addr :0x0000c8    File  Name:videoplayback_32k_32.bin 
#define _JINGLEBELLS3_32K_32           1       	//File  Index:1           File  Name:jinglebells3_32k_32.bin 
#define _JINGLEBELLS3_32K_32_ADDR      (SEC_START_ADDR + 0x019bbe)	//File  Addr :0x019bbe    File  Name:jinglebells3_32k_32.bin 
#define _ESONG6_32K_32                 2       	//File  Index:2           File  Name:esong6_32k_32.bin 
#define _ESONG6_32K_32_ADDR            (SEC_START_ADDR + 0x02cae4)	//File  Addr :0x02cae4    File  Name:esong6_32k_32.bin 
#define _AINT_32K_32                   3       	//File  Index:3           File  Name:aint_32k_32.bin 
#define _AINT_32K_32_ADDR              (SEC_START_ADDR + 0x036a9a)	//File  Addr :0x036a9a    File  Name:aint_32k_32.bin 
#define _VIDEOPLAYBACK_16K_32K         4       	//File  Index:4           File  Name:videoplayback_16K_32K.a181 
#define _VIDEOPLAYBACK_16K_32K_ADDR    (SEC_START_ADDR + 0x04afa0)	//File  Addr :0x04afa0    File  Name:videoplayback_16K_32K.a181 
#define _JINGLEBELLS3_16K_32K          5       	//File  Index:5           File  Name:jinglebells3_16K_32K.a181 
#define _JINGLEBELLS3_16K_32K_ADDR     (SEC_START_ADDR + 0x064456)	//File  Addr :0x064456    File  Name:jinglebells3_16K_32K.a181 
#define _ESONG6_16K_32K                6       	//File  Index:6           File  Name:esong6_16K_32K.a181 
#define _ESONG6_16K_32K_ADDR           (SEC_START_ADDR + 0x07741c)	//File  Addr :0x07741c    File  Name:esong6_16K_32K.a181 
#define _AINT_16K_32K                  7       	//File  Index:7           File  Name:aint_16K_32K.a181 
#define _AINT_16K_32K_ADDR             (SEC_START_ADDR + 0x081382)	//File  Addr :0x081382    File  Name:aint_16K_32K.a181 

#endif /* __FILE_MERGER_H__ */
