#ifndef __FILE_MERGER_H__
#define __FILE_MERGER_H__

/* This file is automatically generated by G+ FileMerger.
   Do not modify the contents to prevent from invalid addressing.
*/ 

#if defined (__GNUC__) || defined (__CC_ARM)  || defined (__ICCARM__) 	/* 32 bit ARM compiler */

	#include <stdint.h>
	#if defined (__CSRC_USED__)					/* use C source instead of elf obj file */
		extern const uint8_t* A1801_FileMerger_bin_Data;
		#define SEC_START_ADDR A1801_FileMerger_bin_Data
	#else
		extern uint8_t _binary_A1801_FileMerger_bin_start;
		extern uint32_t _binary_A1801_FileMerger_bin_size;

		#define SEC_START_ADDR &_binary_A1801_FileMerger_bin_start
	#endif

#else
	#define SEC_START_ADDR 0
#endif

#define _GROUP_TABLE                   0       	//Group Index:0           Group Name:Group_Table     Group Type:Unknown 
#define _GROUP_TABLE_ADDR              (SEC_START_ADDR + 0x000030)	//Group Addr :0x000030    Group Name:Group_Table     Group Type:Unknown 
#define _YOUARETHEREASON2_16K          0       	//File  Index:0           File  Name:youarethereason2_16K.a181 
#define _YOUARETHEREASON2_16K_ADDR     (SEC_START_ADDR + 0x000030)	//File  Addr :0x000030    File  Name:youarethereason2_16K.a181 
#define _SEEYOUAGAIN_16K               1       	//File  Index:1           File  Name:seeyouagain_16K.a181 
#define _SEEYOUAGAIN_16K_ADDR          (SEC_START_ADDR + 0x0104d6)	//File  Addr :0x0104d6    File  Name:seeyouagain_16K.a181 
#define _KYGO_16K                      2       	//File  Index:2           File  Name:kygo_16K.a181 
#define _KYGO_16K_ADDR                 (SEC_START_ADDR + 0x01db14)	//File  Addr :0x01db14    File  Name:kygo_16K.a181 
#define _HELLO2_16K                    3       	//File  Index:3           File  Name:hello2_16K.a181 
#define _HELLO2_16K_ADDR               (SEC_START_ADDR + 0x026062)	//File  Addr :0x026062    File  Name:hello2_16K.a181 
#define _2020BEST32_16K                4       	//File  Index:4           File  Name:2020best32_16K.a181 
#define _2020BEST32_16K_ADDR           (SEC_START_ADDR + 0x033e98)	//File  Addr :0x033e98    File  Name:2020best32_16K.a181 

#endif /* __FILE_MERGER_H__ */
