#ifndef __FILE_MERGER_H__
#define __FILE_MERGER_H__

/* This file is automatically generated by G+ FileMerger.
   Do not modify the contents to prevent from invalid addressing.
*/ 

#if defined (__GNUC__) || defined (__CC_ARM)	/* 32 bit ARM compiler */

	#include <stdint.h>
	#if defined (__CSRC_USED__)					/* use C source instead of elf obj file */
		extern const uint8_t* A34_FileMerger_bin_Data;
		#define SEC_START_ADDR A34_FileMerger_bin_Data
	#else
		extern uint8_t _binary_A34_FileMerger_bin_start;
		extern uint32_t _binary_A34_FileMerger_bin_size;

		#define SEC_START_ADDR &_binary_A34_FileMerger_bin_start
	#endif

#else
	#define SEC_START_ADDR 0
#endif

#define _GROUP_TABLE                   0       	//Group Index:0           Group Name:Group_Table     Group Type:Unknown 
#define _GROUP_TABLE_ADDR              (SEC_START_ADDR + 0x000080)	//Group Addr :0x000080    Group Name:Group_Table     Group Type:Unknown 
#define _DISNEY1                       0       	//File  Index:0           File  Name:disney1.sp4 
#define _DISNEY1_ADDR                  (SEC_START_ADDR + 0x000080)	//File  Addr :0x000080    File  Name:disney1.sp4 
#define _HAPPY                         1       	//File  Index:1           File  Name:happy.sp4 
#define _HAPPY_ADDR                    (SEC_START_ADDR + 0x022fdb)	//File  Addr :0x022fdb    File  Name:happy.sp4 
#define _TK2                           2       	//File  Index:2           File  Name:tk2.sp5 
#define _TK2_ADDR                      (SEC_START_ADDR + 0x0373cd)	//File  Addr :0x0373cd    File  Name:tk2.sp5 

#endif /* __FILE_MERGER_H__ */
