#ifndef __FILE_MERGER_H__
#define __FILE_MERGER_H__

/* This file is automatically generated by G+ FileMerger.
   Do not modify the contents to prevent from invalid addressing.
*/ 

#if defined (__GNUC__) || defined (__CC_ARM)	/* 32 bit ARM compiler */

	#include <stdint.h>
	#if defined (__CSRC_USED__)					/* use C source instead of elf obj file */
		extern const uint8_t* MS02_FileMerger_bin_Data;
		#define SEC_START_ADDR MS02_FileMerger_bin_Data
	#else
		extern uint8_t _binary_MS02_FileMerger_bin_start;
		extern uint32_t _binary_MS02_FileMerger_bin_size;

		#define SEC_START_ADDR &_binary_MS02_FileMerger_bin_start
	#endif

#else
	#define SEC_START_ADDR 0
#endif

#define _GROUP_TABLE                   0       	//Group Index:0           Group Name:Group_Table     Group Type:Unknown 
#define _GROUP_TABLE_ADDR              (SEC_START_ADDR + 0x000034)	//Group Addr :0x000034    Group Name:Group_Table     Group Type:Unknown 
#define _GPCM1F_DEMO                   0       	//File  Index:0           File  Name:GPCM1F_DEMO.lib32 
#define _GPCM1F_DEMO_ADDR              (SEC_START_ADDR + 0x000034)	//File  Addr :0x000034    File  Name:GPCM1F_DEMO.lib32 
#define _007A_MID                      1       	//File  Index:1           File  Name:007a_mid.BIN 
#define _007A_MID_ADDR                 (SEC_START_ADDR + 0x14b23c)	//File  Addr :0x14b23c    File  Name:007a_mid.BIN 
#define _ALLIWANTFORXMAS_1_MID         2       	//File  Index:2           File  Name:AllIWantForXmas_1_mid.BIN 
#define _ALLIWANTFORXMAS_1_MID_ADDR    (SEC_START_ADDR + 0x14e9c2)	//File  Addr :0x14e9c2    File  Name:AllIWantForXmas_1_mid.BIN 
#define _DORAEMON_1_MID                3       	//File  Index:3           File  Name:Doraemon_1_mid.BIN 
#define _DORAEMON_1_MID_ADDR           (SEC_START_ADDR + 0x150a3a)	//File  Addr :0x150a3a    File  Name:Doraemon_1_mid.BIN 
#define _HAKUNAMATATA_MID              4       	//File  Index:4           File  Name:HakunaMatata_mid.BIN 
#define _HAKUNAMATATA_MID_ADDR         (SEC_START_ADDR + 0x153704)	//File  Addr :0x153704    File  Name:HakunaMatata_mid.BIN 
#define _HARRYPOTTER_MID               5       	//File  Index:5           File  Name:HarryPotter_mid.BIN 
#define _HARRYPOTTER_MID_ADDR          (SEC_START_ADDR + 0x155700)	//File  Addr :0x155700    File  Name:HarryPotter_mid.BIN 
#define _LETITGO_2_MID                 6       	//File  Index:6           File  Name:LetItGo_2_mid.BIN 
#define _LETITGO_2_MID_ADDR            (SEC_START_ADDR + 0x15900c)	//File  Addr :0x15900c    File  Name:LetItGo_2_mid.BIN 
#define _NEWYORK_1_MID                 7       	//File  Index:7           File  Name:NewYork_1_mid.BIN 
#define _NEWYORK_1_MID_ADDR            (SEC_START_ADDR + 0x15add6)	//File  Addr :0x15add6    File  Name:NewYork_1_mid.BIN 
#define _SLEIGHRIDE_1_MID              8       	//File  Index:8           File  Name:SleighRide_1_mid.BIN 
#define _SLEIGHRIDE_1_MID_ADDR         (SEC_START_ADDR + 0x15c8e6)	//File  Addr :0x15c8e6    File  Name:SleighRide_1_mid.BIN 
#define _TCHAIKOVSKY_1_MID             9       	//File  Index:9           File  Name:tchaikovsky_1_mid.BIN 
#define _TCHAIKOVSKY_1_MID_ADDR        (SEC_START_ADDR + 0x15f410)	//File  Addr :0x15f410    File  Name:tchaikovsky_1_mid.BIN 
#define _TOY_1_MID                     10      	//File  Index:10          File  Name:toy_1_mid.BIN 
#define _TOY_1_MID_ADDR                (SEC_START_ADDR + 0x16061e)	//File  Addr :0x16061e    File  Name:toy_1_mid.BIN 

#endif /* __FILE_MERGER_H__ */
