#ifndef __FILE_MERGER_H__
#define __FILE_MERGER_H__

/* This file is automatically generated by G+ FileMerger.
   Do not modify the contents to prevent from invalid addressing.
*/ 

#if defined (__GNUC__) || defined (__CC_ARM)	/* 32 bit ARM compiler */

	#include <stdint.h>
	#if defined (__CSRC_USED__)					/* use C source instead of elf obj file */
		extern const uint8_t* A1801_FileMerger_bin_Data;
		#define SEC_START_ADDR A1801_FileMerger_bin_Data
	#else
		extern uint8_t _binary_A1801_FileMerger_bin_start;
		extern uint32_t _binary_A1801_FileMerger_bin_size;

		#define SEC_START_ADDR &_binary_A1801_FileMerger_bin_start
	#endif

#else
	#define SEC_START_ADDR 0
#endif

#define _GROUP_TABLE                   0       	//Group Index:0           Group Name:Group_Table     Group Type:Unknown 
#define _GROUP_TABLE_ADDR              (SEC_START_ADDR + 0x000044)	//Group Addr :0x000044    Group Name:Group_Table     Group Type:Unknown 
#define _01_TESTSTART_WAV              0       	//File  Index:0           File  Name:01_TestStart_wav.a181 
#define _01_TESTSTART_WAV_ADDR         (SEC_START_ADDR + 0x000044)	//File  Addr :0x000044    File  Name:01_TestStart_wav.a181 
#define _02_RECTEST_WAV                1       	//File  Index:1           File  Name:02_RecTest_wav.a181 
#define _02_RECTEST_WAV_ADDR           (SEC_START_ADDR + 0x00086a)	//File  Addr :0x00086a    File  Name:02_RecTest_wav.a181 
#define _03_IOTESTPASS_WAV             2       	//File  Index:2           File  Name:03_IOTestPass_wav.a181 
#define _03_IOTESTPASS_WAV_ADDR        (SEC_START_ADDR + 0x001090)	//File  Addr :0x001090    File  Name:03_IOTestPass_wav.a181 
#define _04_IOTESTFAIL_WAV             3       	//File  Index:3           File  Name:04_IOTestFail_wav.a181 
#define _04_IOTESTFAIL_WAV_ADDR        (SEC_START_ADDR + 0x001bfe)	//File  Addr :0x001bfe    File  Name:04_IOTestFail_wav.a181 
#define _05_X32KTEST_WAV               4       	//File  Index:4           File  Name:05_X32kTest_wav.a181 
#define _05_X32KTEST_WAV_ADDR          (SEC_START_ADDR + 0x0026a4)	//File  Addr :0x0026a4    File  Name:05_X32kTest_wav.a181 
#define _06_DACTEST_WAV                5       	//File  Index:5           File  Name:06_DACTest_wav.a181 
#define _06_DACTEST_WAV_ADDR           (SEC_START_ADDR + 0x002f1a)	//File  Addr :0x002f1a    File  Name:06_DACTest_wav.a181 
#define _07_PWMTEST_WAV                6       	//File  Index:6           File  Name:07_PWMTest_wav.a181 
#define _07_PWMTEST_WAV_ADDR           (SEC_START_ADDR + 0x0038f8)	//File  Addr :0x0038f8    File  Name:07_PWMTest_wav.a181 
#define _08_TESTFINISH_WAV             7       	//File  Index:7           File  Name:08_TestFinish_wav.a181 
#define _08_TESTFINISH_WAV_ADDR        (SEC_START_ADDR + 0x004286)	//File  Addr :0x004286    File  Name:08_TestFinish_wav.a181 
#define _HOWAREYOU_16K                 8       	//File  Index:8           File  Name:howareyou_16K.a181 
#define _HOWAREYOU_16K_ADDR            (SEC_START_ADDR + 0x004a5c)	//File  Addr :0x004a5c    File  Name:howareyou_16K.a181 
#define _BEST_16K                      9       	//File  Index:9           File  Name:best_16K.a181 
#define _BEST_16K_ADDR                 (SEC_START_ADDR + 0x004f8a)	//File  Addr :0x004f8a    File  Name:best_16K.a181 

#endif /* __FILE_MERGER_H__ */
